apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    env: qa
    type: webserver
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
