kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myrs
spec:
 replicas: 3
 selector:
   matchLabels:
     type: webserver
 template:
   metadata:
     name: mypod
     labels:
       type: webserver
   spec:
    containers:
    - name: c1
      image: nginx
